name: My Second file

on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon......" >> dragon.txt

      - name: Show files
        run: ls -ltr
